### PR TITLE
Fix the _default copy behavior to use the correct path

### LINKED ISSUE #18: COPY DEFAULT - Copy default folder at root level of operations repo
The issue is well detailed in the following PR https://github.com/bitops-plugins/helm/pull/17

To make it brief; 
Currently the defaults are being copied from the operations repo environment folder. It should be copied from the root of the operations repo AND it should only match up by chart name. 

**Current behavior**
```
ops_repo
  envA/
    _default/
    chartA/  <-- default folders would be merged into this chart folder
    chartB/  <-- default folders would be merged into this chart folder
      ...      
```

**Expected Behaviour**
```
ops_repo/
  _default/
    helm/ 
      chartA/  <--- Copied into ANY environment depoying the `chartA` chart
  envA/ 
    helm/ 
      chartA/  <--- Matches a chart within the `_defaults` folder which will be merged
      chartB/  <--- Does not match a chart and so will not merge any default folders
```

### PR DESCRIPTION
**Pull request by PhillypHenning**
Fixes https://github.com/bitops-plugins/helm/issues/18

### CODE REVIEW

**Review by arm4b — CHANGES_REQUESTED** [review]
The #9 we're closing with this PR mentions `ERROR and NC seem to be undefined` as the main issue, but this PR is about the `_default` dir.

Could you provide a small sentence in the PR description giving a high-level overview for the PR? Additionally, this looks like a bugfix, - please update the title to be more detailed.

**Comment by PhillypHenning** [comment]
Sure @armab I can move things over

**Comment by PhillypHenning** [comment]
```
DEFAULT_HELM_ROOT=[/tmp/tmpwxvc4adz/03_Demo_Helm/helm/_default]
BITOPS_OPSREPO_ENVIRONMENT_DIR=[/tmp/tmpwxvc4adz/03_Demo_Helm/helm]
BITOPS_DEFAULT_ROOT_DIR=[_default]
DEFAULT_ROOT_DIR=[_default]



01_Demo_Cloudformation
02_Demo_Terraform
03_Demo_Helm
_default



hello-world-chart



Using default folder [/tmp/tmpzasggldo/_default/helm]
Copying defaults....
BITOPS_SCRIPTS_DIR=/opt/bitops/scripts
BITOPS_PLUGINS_DIR=/opt/bitops/scripts/plugins/
BITOPS_CONFIG_SCHEMA=/opt/bitops/scripts/plugins/helm/bitops.schema.yaml
BITOPS_ENVROOT=/tmp/tmpzasggldo/03_Demo_Helm
BITOPS_OPSREPO_ENVIRONMENT_DIR=/tmp/tmpzasggldo/03_Demo_Helm/helm
BITOPS_OPSREPO_ENV_FILE=/tmp/tmpzasggldo/03_Demo_Helm/helm/ENV_FILE
BITOPS_DEFAULT_ROOT_DIR=_default
BITOPS_CONFIG_COMMAND= --namespace=demo-3-testing --timeout=500s
BITOPS_FAIL_FAST=True
BITOPS_KUBE_CONFIG_FILE=/tmp/tmpzasggldo/.kube/config
BITOPS_PLUGIN_DIR=/opt/bitops/scripts/plugins/helm
BITOPS_SCHEMA_ENV_FILE=/tmp/tmpzasggldo/03_Demo_Helm/helm/hello-world-chart/ENV_FILE
BITOPS_ENVIRONMENT=03_Demo_Helm
BITOPS_PLUGIN_NAME=helm
BITOPS_TEMPDIR=/tmp/tmpzasggldo
BITOPS_DIR=/opt/bitops
HELM_BITOPS_CONFIG=/tmp/tmpzasggldo/03_Demo_Helm/helm/hello-world-chart/bitops.config.yaml
```

**Comment by PhillypHenning** [comment]
https://github.com/bitops-plugins/helm/blob/main/scripts/helm_handle_chart.sh#L106

```
# # Identify the default folder for helm
echo "Identify the default root folder for $HELM_CHART helm chart"
if [[ "${DEFAULT_DIR_FLAG}" == "True" ]]; then
    echo "Use 'opsrepo_root_default_dir' of bitops.config.yaml build config value for default root directory..."
    export DEFAULT_HELM_ROOT="$BITOPS_OPSREPO_ENVIRONMENT_DIR/$BITOPS_DEFAULT_ROOT_DIR"
else
    echo "Use 'default-root-dir' of bitops.config.yaml helm chart config value for default root directory..."
    export DEFAULT_HELM_ROOT="$BITOPS_OPSREPO_ENVIRONMENT_DIR/$DEFAULT_ROOT_DIR"
fi
echo "default root folder for $HELM_CHART helm chart found.."

export DEFAULT_HELM_CHART_DIRECTORY="$DEFAULT_HELM_ROOT/$DEFAULT_SUB_DIR"
```

**Comment by PhillypHenning** [comment]
**DEFAULT_HELM_ROOT**
```
BITOPS_OPSREPO_ENVIRONMENT_DIR=/tmp/tmpzasggldo/03_Demo_Helm/helm
BITOPS_DEFAULT_ROOT_DIR=_default
```
DEFAULT_HELM_ROOT: [`/tmp/tmpzasggldo/03_Demo_Helm/helm/_default`

**Comment by PhillypHenning** [comment]
This is the current logic on `main` branch. I don't believe this is correct.

**Comment by PhillypHenning** [comment]
Logic updated to
```
if [[ "${DEFAULT_DIR_FLAG}" == "True" ]]; then
    echo "Use 'opsrepo_root_default_dir' of bitops.config.yaml build config value for default root directory..."
    export DEFAULT_HELM_ROOT="$BITOPS_TEMPDIR/$BITOPS_DEFAULT_ROOT_DIR/$BITOPS_PLUGIN_NAME"
else
    echo "Use 'default-root-dir' of bitops.config.yaml helm chart config value for default root directory..."
    export DEFAULT_HELM_ROOT="$BITOPS_OPSREPO_ENVIRONMENT_DIR/$DEFAULT_ROOT_DIR"
fi

export DEFAULT_HELM_CHART_DIRECTORY="$DEFAULT_HELM_ROOT/$HELM_CHART"
```
**DEFAULT_HELM_CHART_DIRECTORY**
```
DEFAULT_HELM_ROOT=/tmp/tmpixt70rk_/_default/helm/
HELM_CHART=hello-world-chart
```
DEFAULT_HELM_CHART_DIRECTORY: [`/tmp/tmpixt70rk_/_default/helm/hello-world-chart/`]

**Comment by PhillypHenning** [comment]
**tree result before merge**
```
ops_repo/
  _default/
    helm/
      chartA/
        crds/
          crdA.yaml
        templates/
          templateA.yaml
        schema/
          schemaA.yaml
        charts/
          chartA.yaml
    
  dev/
    helm/
      chartA/
```


**tree after merge**
```
ops_repo/
  _default/
    ... remains the same
  dev/
    helm/ 
      chartA/
        crds/
          crdA.yaml
        templates/
          templateA.yaml
        schema/
          schemaA.yaml
        charts/
          chartA.yaml
```

**Comment by PhillypHenning** [comment]
Reviewing https://helm.sh/docs/topics/charts/
I feel like this is what is expected. 

I do question what the `schema` folder is for since that doesn't appear in the doc

**Review by arm4b — APPROVED** [review]
LGTM, Thanks for more details!

**Review by mickmcgrath13 — APPROVED** [review]

**Comment by PhillypHenning** [comment]
Adding backwards comparability assurance (fall back method to retrieve plugin name)

**Logs**
```
Testing...
BITOPS_PLUGIN_NAME:   []
CPATH:                [path/to/helm]
BITOPS_PLUGIN_NAME is empty
BITOPS_PLUGIN_NAME:   [helm]
CPATH:                [path/to/helm]
``` 

**Testing**
```
if [ -z $BITOPS_PLUGIN_NAME ]; then
    echo "BITOPS_PLUGIN_NAME is empty"
    BITOPS_PLUGIN_NAME=$(basename ${CPATH})
fi
```

Updated `helm_handle_charts.sh` with equivalent

**Review by arm4b — APPROVED** [review]
Thanks!

**Pull request merged**
